name: ci

on:
  push:
    branches: [main]
    paths: &paths
      - go.mod
      - go.sum
      - cmd/**
      - internal/**
      - mise.toml
      - .github/workflows/ci.yml
  pull_request:
    paths: *paths

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4
      - run: mise run ci
